config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Devise Routes
  devise_for :users
  # Users Routes
  resources :users
  # Subscriptions Routes
  resources :subscriptions
  # Products Routes
  resources :products
  # Orders Routes
  resources :orders
  # Webpay Routes
  get '/webpayplus/return_url', to: 'orders#webpay_commit', as: :webpay_commit
  get 'webpayplus/status/:token', to: 'orders#webpay_status', as: :webpay_status
  post 'webpayplus/refund', to: 'orders#webpay_refund', as: :webpay_refund
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :subscriptions_products, dependent: :destroy
  has_many :products, through: :subscriptions_products
  accepts_nested_attributes_for :subscriptions_products, allow_destroy: true
  after_save :calculate_total_amount

  def calculate_total_amount
    total_amount = products.sum(:price)
    update_column(:total_amount, total_amount)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]
  before_action :set_products, only: %i[ new edit ]
  before_action :set_is_active, only: %i[ new edit ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def set_products
      @products = Product.all
    end

    def set_is_active
      @is_active = [["Yes", "true"], ["No", "false"]]
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(
        :name,
        :description,
        :total_amount,
        :is_active,
        subscriptions_products_attributes: [
          :id,
          :product_id,
          :_destroy
        ]
      )
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= form_with(model: subscription) do |form| %>
        <% if subscription.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(subscription.errors.count, 'error') %> prohibited this subscription from being saved:</h2>
            <ul>
              <% subscription.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <!--<div class="field">
          <%= form.label :total_amount %>
          <%= form.text_field :total_amount %>
        </div>-->

        <% if coming.eql?(:edit) %>
          <div class="field">
            <%= form.label :is_active %>
            <%= form.select :is_active, is_active, { include_blank: 'Select if the subscription is active' }, { required: true, class: 'form-control' } %>
          </div>
        <% end %>

        <br>
        <hr>
        <br>

        <div class="row mb-5">
          <div class="col-md-12 dynamic-data">
            <label>Add products</label>
            <h2 class="">
              <span class="float-right">
                <%= link_to_add_fields 'Add product', form, :subscriptions_products,'.response_subscriptions_product' %>
              </span>
            </h2>
            <br>
            <div class="response_subscriptions_product">
              <%= form.fields_for :subscriptions_products do |subscriptions_product_fields| %>
                <%= render 'subscriptions_product_fields', f: subscriptions_product_fields %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="actions">
          <%= form.submit 'Save', class: 'btn btn-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/_subscriptions_product_fields.html.erb
<fieldset>
  <div class="row mt-2">
    <div class="col-md-12 card border">
      <div class="card-body">
        <div class="row padding-top">
          <div class="col-lg-12">&nbsp;</div>
          <div class="col-lg-4">
            <div class="field">
              <%= f.collection_select(:product_id, @products, :id, :name, { include_blank: false }, { class: 'form-control' }) %>
            </div>
          </div>
          <div class="col-lg-1">
            <div class="field padding-top-40px">
              <label>&nbsp</label>
              <%= f.hidden_field :_destroy, class: 'destroy_elem' %>
              <%= link_to 'Remove', '#', class: 'remove_fields btn btn-danger' %>
              <%= f.hidden_field :id %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</fieldset>

app/views/subscriptions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>Editing Subscription</h1>
    </div>
  </div>

  <%= render 'form', coming: :edit, subscription: @subscription, is_active: @is_active, products: @products %>
  <br>
  <%= link_to 'Show', @subscription %> |
  <%= link_to 'Back', subscriptions_path %>
</div>
<br>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Subscriptions</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Products</th>
        <th>Total amount</th>
        <th>Is active</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @subscriptions.each do |subscription| %>
        <tr>
          <td><%= subscription.name %></td>
          <td><%= subscription.description %></td>
          <td><%= subscription.products.pluck(:name).join(', ') if subscription.products.present? %></td>
          <td><%= subscription.total_amount ? number_to_currency(subscription.total_amount, delimiter: '.', precision: 0) : '' %></td>
          <td><%= subscription.is_active.eql?(true) ? 'Yes' : 'No' %></td>
          <td><%= link_to 'Show', subscription %></td>
          <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
          <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Subscription', new_subscription_path %>
</div>
<br>

app/views/subscriptions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>New Subscription</h1>
    </div>
  </div>

  <%= render 'form', coming: :new, subscription: @subscription, is_active: @is_active, products: @products %>
  <br>
  <%= link_to 'Back', subscriptions_path %>
</div>
<br>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>Subscription</h1>
    </div>
  </div>
  <br>

  <p>
    <strong>Name:</strong>
    <%= @subscription.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @subscription.description %>
  </p>

  <p>
    <strong>Total amount:</strong>
    <%= @subscription.total_amount %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= @subscription.is_active %>
  </p>

  <p>
    <strong>Products:</strong>
    <%= @subscription.products.pluck(:name).join(', ') if @subscription.products.present? %>
  </p>

  <%= link_to 'Edit', edit_subscription_path(@subscription) %> |
  <%= link_to 'Back', subscriptions_path %>
</div>
<br>